<style type="text/css">
    @import "css/domtab.css";
</style>
<?php
include_once 'includes/columnLeft.php';
?>
<div class="columnSld">
    <div style="width: 99%; background-color: #FC7891; padding-left: 10px; color: #222222; font-size: 16px; border: 1px solid #212121">
        <img src="images/Warning.png" height="30px" width="30px" style="vertical-align: bottom; margin-right: 10px;">
        Sorry, you do not have permission to view this page.
    </div>
</div>
